//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SpecExplorer.VS.Package2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SpecExplorer.VS.Package2.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborting operation. This may take a while to complete..
        /// </summary>
        internal static string AbortingExploration {
            get {
                return ResourceManager.GetString("AbortingExploration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spec Explorer 2010.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building project &apos;{0}&apos;..
        /// </summary>
        internal static string BuildingProjectFormat {
            get {
                return ResourceManager.GetString("BuildingProjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build project &apos;{0}&apos; failed..
        /// </summary>
        internal static string BuildProjectFailedFormat {
            get {
                return ResourceManager.GetString("BuildProjectFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build project &apos;{0}&apos; succeeded..
        /// </summary>
        internal static string BuildProjectSucceededFormat {
            get {
                return ResourceManager.GetString("BuildProjectSucceededFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Generation time of {0} seconds has expired. Please increase the value of switch CodeGenerationTimeout..
        /// </summary>
        internal static string CodeGenerationTimeout {
            get {
                return ResourceManager.GetString("CodeGenerationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution aborted.
        /// </summary>
        internal static string ExecutionAborted {
            get {
                return ResourceManager.GetString("ExecutionAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution finished..
        /// </summary>
        internal static string ExecutionFinished {
            get {
                return ResourceManager.GetString("ExecutionFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploration aborted. Partial exploration result may have inaccurate state/step information..
        /// </summary>
        internal static string ExplorationAborted {
            get {
                return ResourceManager.GetString("ExplorationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploration done..
        /// </summary>
        internal static string ExplorationFinished {
            get {
                return ResourceManager.GetString("ExplorationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploration in progress....
        /// </summary>
        internal static string ExplorationInProgress {
            get {
                return ResourceManager.GetString("ExplorationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploration of machine &apos;{0}&apos; failed..
        /// </summary>
        internal static string ExplorationMachineFailedFormat {
            get {
                return ResourceManager.GetString("ExplorationMachineFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploration of machine &apos;{0}&apos; succeeded..
        /// </summary>
        internal static string ExplorationMachineSucceededFormat {
            get {
                return ResourceManager.GetString("ExplorationMachineSucceededFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploration Manager.
        /// </summary>
        internal static string ExplorationManagerToolWindowTitle {
            get {
                return ResourceManager.GetString("ExplorationManagerToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploring machine &apos;{0}&apos; ....
        /// </summary>
        internal static string ExploringMachineFormat {
            get {
                return ResourceManager.GetString("ExploringMachineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions.
        /// </summary>
        internal static string ExtensionDirectoryName {
            get {
                return ResourceManager.GetString("ExtensionDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to build project: another build process may be already in progress.
        /// </summary>
        internal static string FailedToBuildProject {
            get {
                return ResourceManager.GetString("FailedToBuildProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploration result of machine &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string InvalidMachineExplorationResultFormat {
            get {
                return ResourceManager.GetString("InvalidMachineExplorationResultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All inputs for machine &apos;{0}&apos; are up-to-date..
        /// </summary>
        internal static string MachineResultUpToDateFormat {
            get {
                return ResourceManager.GetString("MachineResultUpToDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-The-Fly replay aborted..
        /// </summary>
        internal static string OnTheFlyReplayAborted {
            get {
                return ResourceManager.GetString("OnTheFlyReplayAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-The-Fly replay finished..
        /// </summary>
        internal static string OnTheFlyReplayFinished {
            get {
                return ResourceManager.GetString("OnTheFlyReplayFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-The-Fly replay in progress....
        /// </summary>
        internal static string OnTheFlyReplayInProgress {
            get {
                return ResourceManager.GetString("OnTheFlyReplayInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-The-Fly test aborted..
        /// </summary>
        internal static string OnTheFlyTestAborted {
            get {
                return ResourceManager.GetString("OnTheFlyTestAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-The-Fly test finished..
        /// </summary>
        internal static string OnTheFlyTestFinished {
            get {
                return ResourceManager.GetString("OnTheFlyTestFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-The-Fly test in progress..
        /// </summary>
        internal static string OnTheFlyTestInProgress {
            get {
                return ResourceManager.GetString("OnTheFlyTestInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} aborted..
        /// </summary>
        internal static string PostProcessorAborted {
            get {
                return ResourceManager.GetString("PostProcessorAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} cannot be saved because it is write-protected. Do you want to remove the write-protection and overwrite the file?.
        /// </summary>
        internal static string SaveOfReadOnlyFileFormat {
            get {
                return ResourceManager.GetString("SaveOfReadOnlyFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.SpecExplorer.VS.Package.dll.
        /// </summary>
        internal static string SEMainAssemblyName {
            get {
                return ResourceManager.GetString("SEMainAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping machine &apos;{0}&apos; because build project &apos;{1}&apos; failed..
        /// </summary>
        internal static string SkippingFailedProjectMachineFormat {
            get {
                return ResourceManager.GetString("SkippingFailedProjectMachineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping machine &apos;{0}&apos; because cannot retrieve model project of the machine..
        /// </summary>
        internal static string SkippingNoProjectMachineFormat {
            get {
                return ResourceManager.GetString("SkippingNoProjectMachineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spec Explorer.
        /// </summary>
        internal static string SpecExplorer {
            get {
                return ResourceManager.GetString("SpecExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Comparison.
        /// </summary>
        internal static string StateComparisonWindowTitle {
            get {
                return ResourceManager.GetString("StateComparisonWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Browser.
        /// </summary>
        internal static string StatesBrowserToolWindowTitle {
            get {
                return ResourceManager.GetString("StatesBrowserToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Browser.
        /// </summary>
        internal static string StepBrowserToolWindow {
            get {
                return ResourceManager.GetString("StepBrowserToolWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;title&gt;Explored Machine(s) Summary&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        BODY
        ///        {
        ///            background-color: white;
        ///            font-family: &quot;Verdana&quot; , sans-serif;
        ///            font-size: 100%;
        ///            margin-left: 0px;
        ///            margin-top: 0px;
        ///        }
        ///        P
        ///        {
        ///            font-family: &quot;Verdana&quot; ,sans-serif;
        ///            font-size: 80%;
        ///            line-height: 12pt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SummaryTemplate {
            get {
                return ResourceManager.GetString("SummaryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test code generation is aborted..
        /// </summary>
        internal static string TestCodeGenerationAborted {
            get {
                return ResourceManager.GetString("TestCodeGenerationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate test code for machine &apos;{0}&apos;..
        /// </summary>
        internal static string TestCodeGenerationFailedFormat {
            get {
                return ResourceManager.GetString("TestCodeGenerationFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test code generation of machine &apos;{0}&apos; is in progress ....
        /// </summary>
        internal static string TestCodeGenerationInProgressFormat {
            get {
                return ResourceManager.GetString("TestCodeGenerationInProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test code generation of machine &apos;{0}&apos; succeeded..
        /// </summary>
        internal static string TestCodeGenerationSucceededFormat {
            get {
                return ResourceManager.GetString("TestCodeGenerationSucceededFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploration Result.
        /// </summary>
        internal static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating machine &apos;{0}&apos; ....
        /// </summary>
        internal static string ValidatingMachineFormat {
            get {
                return ResourceManager.GetString("ValidatingMachineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed (see error list)..
        /// </summary>
        internal static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation in progress ....
        /// </summary>
        internal static string ValidationInProgress {
            get {
                return ResourceManager.GetString("ValidationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation of machine &apos;{0}&apos; failed..
        /// </summary>
        internal static string ValidationMachineFailedFormat {
            get {
                return ResourceManager.GetString("ValidationMachineFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation of machine &apos;{0}&apos; succeeded..
        /// </summary>
        internal static string ValidationMachineSucceededFormat {
            get {
                return ResourceManager.GetString("ValidationMachineSucceededFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation succeeded..
        /// </summary>
        internal static string ValidationSucceeded {
            get {
                return ResourceManager.GetString("ValidationSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.seguidance.
        /// </summary>
        internal static string WorkflowFileExtension {
            get {
                return ResourceManager.GetString("WorkflowFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed loading Modeling Guidance from file :.
        /// </summary>
        internal static string WorkflowLoadingFailure {
            get {
                return ResourceManager.GetString("WorkflowLoadingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidance.
        /// </summary>
        internal static string WorkflowsDirectory {
            get {
                return ResourceManager.GetString("WorkflowsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spec Explorer Modeling Guidance.
        /// </summary>
        internal static string WorkflowToolWindowTitle {
            get {
                return ResourceManager.GetString("WorkflowToolWindowTitle", resourceCulture);
            }
        }
    }
}
